version: '2'

services:
  spark:
    build: ./dockerfiles/spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'

  spark-worker-1:
    build: ./dockerfiles/spark
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - '8081:8081'
      - '4041:4040'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_PUBLIC_DNS=127.0.0.1
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    build: ./dockerfiles/spark
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - '8082:8082'
      - '4042:4040'
    environment:
      - SPARK_PUBLIC_DNS=127.0.0.1
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-3:
    build: ./dockerfiles/spark
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - '8083:8083'
      - '4043:4040'
    environment:
      - SPARK_PUBLIC_DNS=127.0.0.1
      - SPARK_WORKER_WEBUI_PORT=8083
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-4:
    build: ./dockerfiles/spark
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - '8084:8084'
      - '4044:4040'
    environment:
      - SPARK_PUBLIC_DNS=127.0.0.1
      - SPARK_WORKER_WEBUI_PORT=8084
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  jupyter:
    build: ./dockerfiles/jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
    user: root
    ports:
      - '8888:8888'
      - '4040:4040'
    environment:
      - SPARK_PUBLIC_DNS=127.0.0.1
      - GRANT_SUDO=yes